# Custom Language File for Launcher Customizer

[ejs.app]
title = "Viking RP"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://www.youtube.com/@VikingRoleplay"
mediaDiscordURL = "https://discord.com/invite/viking-rp-maintenance-535476824734564372"

[ejs.settings]
sourceGithubLink = "#"
supportLink = "#"

[ejs.welcome]
welcomeHeader = "Bonjour Viking"
welcomeDescription = "Plongez dans un monde d'inspiration médiévale renaissance, où des nations uniques, des problématiques complexes et des peuplades fascinantes coexistent dans une danse perpétuelle de conflits et d'alliances."
welcomeDescCTA = "La politique, la guerre, le commerce, l'exploration et le complot sont autant de facettes qui composent la trame de Ravengard"
